fragment HomeParts on Home {
  __typename
  hero {
    __typename
    logo
    title
    subtitle
    taglines {
      __typename
      text
    }
    scripture
    scriptureRef
    ctas {
      __typename
      label
      href
      primary
    }
  }
  nav {
    __typename
    links {
      __typename
      label
      href
    }
  }
  sections {
    __typename
    ... on HomeSectionsListSection {
      heading
      intro
      introEmphasis
      groups {
        __typename
        lead
        items {
          __typename
          text
        }
      }
      closing
      closingEmphasis
      scripture
      scriptureRef
      background
      cta {
        __typename
        label
        href
      }
    }
  }
}
